### PR TITLE
Support native javascript class

### PR DESCRIPTION
**Pull request by oliverlj**
#15

### CODE REVIEW

**Comment by oliverlj** [comment]
works as well with acorn 8, and "ecmaVersion: 2022,"

**Comment by GreatWizard** [comment]
Your patch works well :)

**Comment by GreatWizard** [comment]
ping @rupdegraff Do you think you can add it in master and release it? 🙏

**Comment by rupdegraff** [comment]
@oliverlj thank you for your contributions to `SitemapAutogenerator` and sorry for the long delay in responding. When I tried running your PR, I received the following regardless of whether I used `npm` or `yarn`:

image

My guess is that you and @GreatWizard already had `acorn` **and** `acorn-class-fields` as project dependencies. After getting this error, I added the following to `SitemapAutogenerator`'s `package.json`:

image

and then generated a new `package-lock.json`. These changes brought `acorn-class-fields` into my project's dependencies. Would you like to resolve the conflicts above by accepting the current `package-lock.json` and `package.json` from `SitemapAutogenerator`'s `master` branch and I'll test your changes again. Thanks!

**Review by rupdegraff — APPROVED** [review]

**Pull request merged**
